language: python
python:
  - "3.6"

install:
  - make install
  - pip install -U pytest pytest-cov codecov

script:
  - make test-cov

after_success:
  - codecov

deploy:
  provider: pypi
  username: $TWINE_USERNAME
  password: $TWINE_PASSWORD
  on:
    tags: true
